import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../components/styles/globals.css";
import { NextLayout, NextProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextProvider>
          <NextLayout>
            {children}
            {modal}
            <div id="modal-root" />
          </NextLayout>
        </NextProvider>
      </body>
    </html>
  );
}
